CREATE TABLE INGREDIENT (
IngredientID Int AUTO_INCREMENT NOT NULL,
IngredientName Char(25) NOT NULL,
Quantity Int NULL,
IngredientURL Char(200),
CONSTRAINT INGREDIENT_PK PRIMARY KEY (IngredientID)
);

CREATE TABLE RECIPE (
RecipeID Int AUTO_INCREMENT NOT NULL,
RecipeName Char(30) NOT NULL,
Directions Char(255) NOT NULL,
Notes Char(255) NULL,
CONSTRAINT RECIPE_PK PRIMARY KEY (RecipeID)
);

CREATE TABLE USER (
UserID Int AUTO_INCREMENT NOT NULL,
UserName Char(30) NOT NULL,
Password Char(30) NOT NULL,
Email Char(30) NOT NULL,
Phone Char(30) NOT NULL,
City Char(30) NOT NULL,
CONSTRAINT USER_PK PRIMARY KEY (UserID)
);